/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import controler.ProjectController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Project;
import util.ConnectionFactory;
import java.time.LocalDateTime;

public class App {

    public static void main(String[] args) {
        /*
        Teste de gravação de projeto
        */
        
        Project prj01 = new Project() ;   

        /*
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        LocalDateTime dateNow = LocalDateTime.now();
        System.out.println("data gerada:" + formatter.format(dateNow));
        prj01.setName("nome 01");
        prj01.setDescription("desc 01");
        prj01.setCreationAt(dateNow);
        prj01.setUpdatedAt(dateNow);
        
        ProjectController pc = new ProjectController();
        pc.save(prj01);
        */
        
    }
}
