/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import java.sql.Connection;
import util.ConnectionFactory;

public class App {

    public static void main(String[] args) {
        Connection con = ConnectionFactory.getConnection();
        
        ConnectionFactory.closeConection(con);
    }
}
